### ISSUE TITLE
how to receive notification message content (body, title) from push kit sdk

### ISSUE THREAD

**Issue by jasonleewj85** [onurkenis/reactnative-hms-birdge#1]
onMessageReceived no trigger when sending notification message but working when sending data message.

**Comment by onurkenis** [comment]
Hi, onMessageReceived is only for data messages, you can check following [https://developer.huawei.com/consumer/en/doc/development/HMS-References/push-HmsMessageService-cls](url). You can try to implement a work arround for handling data with intent
